import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Link from "next/link";
import { getSession } from "@auth0/nextjs-auth0";
import Image from "next/image";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const user = session?.user;

  return (
    <html lang="en">
      <UserProvider>
        <body className={roboto.className}>
          <nav>
            <h1 className=" font-semibold text-3xl font-serif"> Kaufy </h1>
            {user ? (
              <div className="flex items-center gap-4 justify-end w-full">
                <div className="flex items-center gap-4">
                  <Image
                    src={user.picture || "/default-profile.png"}
                    alt={user.name || "User"}
                    width={50}
                    height={50}
                    className="rounded-full"
                  />
                  <h2>
                    {user.name.charAt(0).toUpperCase() +
                      user.name.slice(1).toLowerCase()}
                  </h2>
                </div>
                <Link
                  href={"api/auth/logout"}
                  className="bg-blue-300
                px-4 py-2 rounded-2xl"
                >
                  Logout
                </Link>
              </div>
            ) : (
              <Link
                className="bg-blue-300
                px-4 py-2 rounded-2xl"
                href={"api/auth/login"}
              >
                Login
              </Link>
            )}{" "}
          </nav>
          <main className="">{children}</main>
        </body>
      </UserProvider>
    </html>
  );
}
